name: c

on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * *"
  

permissions:
  contents: write

jobs:

  build:
  
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: Install python-abp
      run: |
        python -m pip install --upgrade pip
        pip install python-abp
    - name: Build
      run: |
        flrender $GITHUB_WORKSPACE/c.template $GITHUB_WORKSPACE/c.txt
    - name: Commit and push changes
      run: |
        git config user.name "github-actions[bot]"
        git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
        git add .
        git commit -m "Update c.txt"
        git push
      env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
